# Generated by Django 5.2.2 on 2025-11-04 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('tipo_mercado', models.CharField(choices=[('ACCIONES', 'acciones'), ('CFI', 'CFI'), ('FONDOS_MUTUOS', 'Fondos_Mutuos')], max_length=20)),
                ('origen_informacion', models.CharField(choices=[('CORREDORA', 'Corredora'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('periodo_comercial', models.PositiveBigIntegerField()),
                ('mappingJson', models.JSONField()),
                ('factoresJson', models.JSONField(default=dict)),
                ('descripcion', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('validacion', 'Validación'), ('negocio', 'Negocio')], max_length=50)),
                ('expresion', models.CharField(max_length=500)),
                ('severidad', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=100)),
                ('antes', models.JSONField(blank=True, null=True)),
                ('despues', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField(verbose_name='Año/Ejercicio')),
                ('mercado', models.CharField(default='AC', max_length=50, verbose_name='Mercado')),
                ('instrumento', models.CharField(max_length=100, verbose_name='Instrumento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_pago', models.DateField(default=None, verbose_name='Fecha de Pago')),
                ('secuencia_evento', models.CharField(max_length=50, verbose_name='Secuencia de Evento')),
                ('evento_capital', models.CharField(blank=True, max_length=100, verbose_name='Evento de Capital')),
                ('valor_historico', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Histórico')),
                ('dividendo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Dividendo')),
                ('factores', models.JSONField(default=dict, help_text='Diccionario con factores del 8 al 37', verbose_name='Factores Tributarios')),
                ('factores_calculados', models.JSONField(blank=True, default=dict, help_text='Resultado de cálculos automáticos', verbose_name='Factores Calculados')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('completado', 'Completado'), ('error', 'Error')], default='borrador', max_length=20)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('sistema', 'Sistema'), ('carga_masiva', 'Carga Masiva')], default='manual', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('errores_validacion', models.JSONField(blank=True, default=list, verbose_name='Errores de Validación')),
                ('creado_por', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('cambios', models.JSONField(default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app_nuam.calificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Calificación',
                'verbose_name_plural': 'Historiales de Calificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LoteCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('en proceso', 'En Proceso'), ('procesado', 'Procesado'), ('error', 'Error')], default='en proceso', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='lote_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_nuam.lotecarga', verbose_name='Lote de Carga Origen'),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(default=False, upload_to='uploads/')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=30)),
                ('hash', models.CharField(max_length=200, unique=True)),
                ('estado', models.CharField(max_length=50)),
                ('lote_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nuam.lotecarga')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('nivel', models.CharField(max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroBruto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payloadJson', models.JSONField()),
                ('erroresJson', models.JSONField(blank=True, null=True)),
                ('valido', models.BooleanField(default=False)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nuam.archivo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroNormalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.PositiveIntegerField(default=2025)),
                ('instrumento', models.CharField(max_length=100)),
                ('fecha_pago_dividendo', models.DateField()),
                ('descripcion_dividendo', models.TextField()),
                ('secuencia_evento', models.CharField(max_length=20)),
                ('acogido_isfut', models.CharField(blank=True, max_length=10, null=True)),
                ('origen', models.CharField(max_length=20)),
                ('factor_actualizacion', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('factores', models.JSONField(blank=True, null=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nuam.archivo')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nuam.plantilla')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='registro_normalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_nuam.registronormalizado', verbose_name='Registro Normalizado Origen'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('urlDescarga', models.URLField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registroNormalizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nuam.registronormalizado')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nuam.regla')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin'), ('analista', 'Analista'), ('contador', 'Contador'), ('auditor', 'Auditor')], default='usuario', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['ejercicio', 'mercado'], name='app_nuam_ca_ejercic_713cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['estado'], name='app_nuam_ca_estado_0b4922_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['fecha_pago'], name='app_nuam_ca_fecha_p_83d066_idx'),
        ),
    ]
