# Generated by Django 5.2.2 on 2025-10-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin'), ('analista', 'Analista'), ('contador', 'Contador'), ('auditor', 'Auditor')], default='usuario', max_length=255),
        ),
    ]
