# Generated by Django 5.2.7 on 2025-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='origen_informacion',
            field=models.CharField(choices=[('manual', 'Manual'), ('sistema', 'Sistema'), ('carga_masiva', 'Carga Masiva')], max_length=20),
        ),
    ]
