# Generated by Django 5.2.2 on 2025-10-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0002_alter_userprofile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(default=False, upload_to='uploads/'),
        ),
    ]
