# Generated by Django 5.2.2 on 2025-10-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0003_archivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='hash',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
