# Generated by Django 5.2.7 on 2025-11-03 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0004_alter_archivo_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('cambios', models.JSONField(default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Calificación',
                'verbose_name_plural': 'Historiales de Calificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Calificación Tributaria', 'verbose_name_plural': 'Calificaciones Tributarias'},
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='label',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='motivos',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='objetoId',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='objetoTipo',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='score',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='creado_por',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='dividendo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Dividendo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='ejercicio',
            field=models.IntegerField(default=2025, verbose_name='Año/Ejercicio'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='errores_validacion',
            field=models.JSONField(blank=True, default=list, verbose_name='Errores de Validación'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('completado', 'Completado'), ('error', 'Error')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evento_capital',
            field=models.CharField(blank=True, max_length=100, verbose_name='Evento de Capital'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factores',
            field=models.JSONField(default=dict, help_text='Diccionario con factores del 8 al 37', verbose_name='Factores Tributarios'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factores_calculados',
            field=models.JSONField(blank=True, default=dict, help_text='Resultado de cálculos automáticos', verbose_name='Factores Calculados'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fecha_pago',
            field=models.DateField(default=None, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='instrumento',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='lote_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_nuam.lotecarga', verbose_name='Lote de Carga Origen'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='mercado',
            field=models.CharField(default='AC', max_length=50, verbose_name='Mercado'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('sistema', 'Sistema'), ('carga_masiva', 'Carga Masiva')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='registro_normalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_nuam.registronormalizado', verbose_name='Registro Normalizado Origen'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='secuencia_evento',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Secuencia de Evento'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='valor_historico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Histórico'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['ejercicio', 'mercado'], name='app_nuam_ca_ejercic_713cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['estado'], name='app_nuam_ca_estado_0b4922_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['fecha_pago'], name='app_nuam_ca_fecha_p_83d066_idx'),
        ),
        migrations.AddField(
            model_name='historialcalificacion',
            name='calificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app_nuam.calificacion'),
        ),
        migrations.AddField(
            model_name='historialcalificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
