# Generated by Django 5.2.7 on 2025-11-01 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0004_alter_archivo_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='descripcion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='factoresJson',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantilla',
            name='origen_informacion',
            field=models.CharField(choices=[('CORREDORA', 'Corredora'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantilla',
            name='periodo_comercial',
            field=models.PositiveBigIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantilla',
            name='tipo_mercado',
            field=models.CharField(choices=[('ACCIONES', 'acciones'), ('CFI', 'CFI'), ('FONDOS_MUTUOS', 'Fondos_Mutuos')], default='ACCIONES', max_length=20),
            preserve_default=False,
        ),
    ]
