# Generated by Django 5.2.2 on 2025-11-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0005_plantilla_activo_plantilla_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registronormalizado',
            name='fechaDoc',
        ),
        migrations.RemoveField(
            model_name='registronormalizado',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='registronormalizado',
            name='neto',
        ),
        migrations.RemoveField(
            model_name='registronormalizado',
            name='rutEmisor',
        ),
        migrations.RemoveField(
            model_name='registronormalizado',
            name='rutReceptor',
        ),
        migrations.RemoveField(
            model_name='registronormalizado',
            name='tipoDocumento',
        ),
        migrations.RemoveField(
            model_name='registronormalizado',
            name='total',
        ),
        migrations.AddField(
            model_name='registronormalizado',
            name='acogido_isfut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registronormalizado',
            name='descripcion_dividendo',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registronormalizado',
            name='ejercicio',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registronormalizado',
            name='factor_actualizacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registronormalizado',
            name='factores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registronormalizado',
            name='fecha_pago_dividendo',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registronormalizado',
            name='instrumento',
            field=models.CharField(default='nada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registronormalizado',
            name='origen',
            field=models.CharField(default='no', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registronormalizado',
            name='secuencia_evento',
            field=models.CharField(default='no', max_length=20),
            preserve_default=False,
        ),
    ]
