# Generated by Django 5.2.2 on 2025-11-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0006_remove_registronormalizado_fechadoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronormalizado',
            name='ejercicio',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
