# Generated by Django 5.2.2 on 2025-11-03 01:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0007_alter_registronormalizado_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronormalizado',
            name='fecha_pago_dividendo',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
