# Generated by Django 5.2.2 on 2025-11-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0008_alter_registronormalizado_fecha_pago_dividendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registronormalizado',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nuam.archivo'),
        ),
    ]
