# Generated by Django 4.2.25 on 2025-11-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nuam', '0005_historialcalificacion_alter_calificacion_options_and_more'),
        ('app_nuam', '0009_registronormalizado_archivo'),
    ]

    operations = [
    ]
